dock_dir ='/home/malgorzata/Desktop/rDock_2013.1_src'
chimera_dir ='/home/malgorzata/chimera/bin'
work_dir ='/home/malgorzata/Desktop/rDOCK_IFD/test'
receptor ='2acr'
apo ='2acr'
ligand ='TOL'
rec_ligand ='NAP'
no_poses ='10'
act_chain ='A'

soft = 'soft_docking.prm' 
hard = 'hard_docking.prm' 
rec_chain = 'A'
