dock_dir ='/home/malgorzata/Desktop/rDock_2013.1_src'
chimera_dir ='/home/malgorzata/chimera/bin'
work_dir ='/home/malgorzata/Desktop/rDOCK_IFD/test3'
receptor ='3pgh'
apo ='3pgh'
ligand ='S58'
rec_ligand ='HMD'
no_poses ='10'
act_chain ='A'

soft = 'soft_docking.prm' 
hard = 'hard_docking.prm' 
rec_chain = 'A'
