dock_dir ='/home/malgorzata/Desktop/rDock_2013.1_src'
chimera_dir ='/home/malgorzata/chimera/bin'
work_dir ='/home/malgorzata/Desktop/rDOCK_IFD/test14'
receptor ='2prg'
apo ='2prg'
ligand ='570'
rec_ligand ='BRL'
no_poses ='10'
act_chain ='A'



soft = 'soft_docking.prm' 
hard = 'hard_docking.prm' 
rec_chain = 'A'
best_pose= 'model6_opt'
work_dir='/home/malgorzata/Desktop/rDOCK_IFD/test14/IFD'
receptor ='ligand_remove'
best_score ='model6'
best_score2 ='model3'
best_pose2 ='pose3'
