dock_dir ='/home/malgorzata/Desktop/rDock_2013.1_src'
chimera_dir ='/home/malgorzata/chimera/bin'
work_dir ='/home/malgorzata/Desktop/rDOCK_IFD/Wyniki/14a_ppar-gamma'
receptor ='2prg'
apo ='2prg'
ligand ='570'
rec_ligand ='BRL'
no_poses ='10'
act_chain ='A'


soft = 'soft_docking.prm' 
hard = 'hard_docking.prm' 
rec_chain = 'A'
best_pose= 'model2_opt'
work_dir='/home/malgorzata/Desktop/rDOCK_IFD/Wyniki/14a_ppar-gamma/IFD'
receptor ='ligand_remove'
best_score ='model2'
best_score2 ='model8'
best_pose2 ='pose8'
